---
ID: "e31b15fe-a4c8-4728-bf5d-2c6043c3db31"
Parent: "7c250008-5f3c-456a-81c8-912ef0a4d11e"
Template: "7c250008-5f3c-456a-81c8-912ef0a4d11e"
Path: /sitecore/templates/Project/VisitUs/Pages/Listings/Restaurants/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: "{63FBEB4C-C232-434F-BF0B-D11B29AB64E0}"
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Type: layout
  Value: |
    <r xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        l="{8E6B0A7F-A127-4F35-A57C-2E6B4988F114}" />
    </r>
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220211T121629Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
